addiction = {
"alcoholism": 1,
"alcohol": 1,
"drug": 1,
"drugs": 1,
"cancer": 1,
"craving": 1,
"obsession": 1,
"amphetamine": 1,
"methadone": 1,
"psychotherapy": 1,
"reward system": 1,
"nicotine": 1,
"habituation": 1,
"habit": 1,
"cocaine": 1,
"drugs": 1,
"abuse": 1,
"abused": 1,
"abuses": 1,
"adolesce": 1,
"adolescence": 1,
"adolescent": 1,
"drug addiction": 1,
"cocaine addiction": 1,
"overexpression": 1,
"biomarker": 1,
"relapse": 1,
"insomnia": 1,
"rehab": 1,
"psychosis": 1,
"homelessness": 1,
"substance abuse": 1,
"positive reinforcement": 1,
"food addiction": 1,
"chocolate": 1,
"chocoholic": 1,
"video game addiction": 1,
"anxiety": 1,
"anxiety attack": 1,
"gambling addiction": 1,
"sexual addiction": 1,
"drug withdrawal": 1,
"depression": 1,
"heroin": 1,
"body": 1,
"pathology": 1,
"mind": 1,
"methamphetamine": 1,
"accident": 1,
"award": 1,
"awarding": 1,
"narcotic": 1,
"sequela": 1,
"viral vector": 1,
"cigarette": 1,
"obesity": 1,
"addicted": 1,
"detox": 1,
"addicts": 1,
"pathophysiology": 1,
"chronic": 1,
"cure": 1,
"therapy": 1,
"arthritis": 1,
"childhood": 1,
"brain disorder": 1,
"painkiller": 1,
"painkiller overdose": 1,
"detoxification": 1,
"medications": 1,
"treating": 1,
"meth": 1,
"distress": 1,
"hiv": 1,
"infections": 1,
"treatment": 1,
"treat": 1,
"treating": 1,
"prescription": 1,
"smoking": 1,
"heartbeat": 1,
"treatments": 1,
"caffeine": 1,
"obsessive compulsive": 1,
"obsessive": 1,
"poisoning": 1,
"allergy": 1,
"hunger": 1,
"misuse": 1,
"diseases": 1,
"disease": 1,
"diseased": 1,
"leukemia": 1,
"counseling": 1,
"relinece": 1,
"disorder": 1,
"abusers": 1,
"helplessness": 1,
"debilitated": 1,
"epilepsy": 1,
"viral": 1,
"suffers": 1,
"antiretroviral": 1,
"lozenge": 1,
"infertility": 1,
"emergency medical services": 1,
"impotence": 1,
"ailments": 1,
"overdose": 1,
"injecting": 1,
"pills": 1,
"comorbid": 1,
"inducing": 1,
"lung cancer": 1,
"epidemic": 1,
"sensory": 1,
"sensorying": 1,
"vice": 1,
"flaw": 1,
"flawed": 1,
"tobacco products": 1,
"poisonous": 1,
"liver cirrhosis": 1,
"alcohol-related dementia": 1,
"methylphenidate": 1,
"white plague": 1,
"civil law": 1,
"opiates": 1,
"amphetamine addiction": 1,
"bulimia": 1
}