childdisorders = {
	"children": 1,
	"child": 1,
	"disorders": 1,
	"among": 1,
	"typically": 1,
	"learn": 1,
	"cause": 1,
	"distress": 1,
	"problems": 1,
	"serious": 1,
	"change": 1,	
	"changes": 1,	
	"learned": 1,	
	"learning": 1,
	"described": 1,
	"describe": 1,
	"diagnose": 1,
	"mental": 1,
	"health": 1,
	"seen": 1,
	"sad": 1,
	"feel": 1,	
	"feeling": 1,	
	"hopeless": 1,	
	"life": 1,	
	"uninterested": 1,	
	"uninterest": 1,	
	"things": 1,	
	"helpless": 1,	
	"enjoy": 1,	
	"sadness": 1,	
	"hopelessness": 1,	
	"diagnosed": 1,	
	"depression": 1,	
	"persistent": 1,	
	"sadness": 1,	
	"behaviors": 1,	
	"depression": 1,	
	"irritable": 1,	
	"time": 1,	
	"wanting": 1,	
	"fun": 1,	
	"eating": 1,	
	"eat": 1,	
	"patterns": 1,	
	"more": 1,	
	"less ": 1,	
	"usual": 1,	
	"Showing": 1,	
	"Show": 1,	
	"changes": 1,	
	"normal": 1,	
	"sleeping": 1,	
	"sleep": 1,	
	"energy": 1,	
	"tired ": 1,	
	"sluggish": 1,	
	"being": 1,	
	"be": 1,	
	"restless": 1,	
	"tense": 1,	
	"hard": 1,	
	"paying ": 1,	
	"pay": 1,	
	"worthless": 1,	
	"useless": 1,	
	"guilty": 1,	
	"Showing": 1,	
	"Show": 1,	
	"injury": 1,	
	"destructive ": 1,	
	"behavior": 1,	
	"attention": 1,	
	"talk": 1,	
	"thoughts": 1,	
	"talking": 1,	
	"their": 1,	
	"appear": 1,	
	"Depression": 1,	
	"make": 1,	
	"trouble": 1,	
	"act": 1,	
	"unmotivated": 1,	
	"causing": 1,	
	"others": 1,	
	"notice": 1,	
	"incorrectly": 1,	
	"label ": 1,	
	"maker": 1,	
	"lazy": 1,	
	"important": 1,	
	"can": 1,	
	"especially": 1,		
	"addition ": 1,	
	"right ": 1,	
	"getting ": 1,	
	"get": 1,	
	"treatment": 1,	
	"leading ": 1,	
	"lead": 1,	
	"lifestyle ": 1,	
	"role ": 1,	
	"managing ": 1,	
	"manage": 1,	
	"symptoms ": 1,	
	"centered ": 1,	
	"center": 1,	
	"fruits": 1,	
	"legumes ": 1,	
	"lean ": 1,	
	"protein ": 1,
	"sources": 1,	
	"nuts ": 1,
	"seeds": 1,
	"Participating ": 1,
	"physical ": 1,	
	"activity": 1,
	"recommended ": 1,	
	"amount ": 1,	
	"night ": 1,	
	"based ": 1,	
	"age": 1,	
	"Practicing ": 1,	
	"mindfulness ": 1,	
	"relaxation ": 1,	
	"techniques": 1,	
	"under ": 1,	
	"exposed": 1,	
	"abuse ": 1,	
	"neglect ": 1,	
	"parent": 1,	
	"caregiver": 1,	
	"person ": 1,	
	"custodial ": 1,	
	"teacher": 1,	
	"emotional ": 1
}